name: 'MemeServe Image Processor'
description: 'Handles the Processing of Image for MemeServe'
outputs:
  file-io-url:
    description: File IO One-Time Download URL
runs:
  using: node12
  main: index.js